### ISSUE TITLE
(Postgrex.Error) ERROR 42P01 (undefined_table) relation "sessions" does not exist

### ISSUE THREAD

**Issue by melt7777** [kkoralsky/tmate-docker-compose#1]
Hi kkoralsky, thanks for this great docker-compose. We are hoping to get the self-hosted cluster running soon, but are facing issue where the sessions relation is not available and cannot complete migrations step.

In the output you will see the above followed by cancelling out of that, and starting the rest of the services to examine the logs output. More errors related to sessions. 

Please advise as to how to proceed. 

Thanks so much!!

~ melt

 

```
[root@support tmate]# rm /var/lib/docker/volumes/tmate_postgres_data/_data/* -rf
[root@support tmate]# docker-compose pull
Pulling master    ... done
Pulling ssh       ... done
Pulling websocket ... done
Pulling postgres  ... done
[root@support tmate]# docker-compose up -d postgres
Creating network "tmate_default" with the default driver
Creating tmate_postgres_1 ... done
[root@support tmate]# docker-compose run master ./bin/tmate console
Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

16:03:18.347 [info] [swarm on tmate@erl_node_name] [tracker:init] started
16:03:18.428 [info] Running TmateWeb.Endpoint with cowboy 2.7.0 at 0.0.0.0:4000 (http)
16:03:18.432 [info] Access TmateWeb.Endpoint at http://tmate.miner.farm:4000
Interactive Elixir (1.9.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(tmate@erl_node_name)1>
nil
iex(tmate@erl_node_name)2> 16:03:23.348 [info] [swarm on tmate@erl_node_name] [tracker:cluster_wait] joining cluster..
16:03:23.348 [info] [swarm on tmate@erl_node_name] [tracker:cluster_wait] no connected nodes, proceeding without sync

nil
iex(tmate@erl_node_name)3> % Mix.Task.rerun("ecto.migrate", ["-r", Tmate.Repo, "--migrations-path", "./lib/tmate-0.1.1/priv/repo/migrations"])
...(tmate@erl_node_name)3>
...(tmate@erl_node_name)3>
...(tmate@erl_node_name)3> ?
warning: found ? followed by code point 0xA (newline), please use ?\n instead
  iex:6

** (SyntaxError) iex:6: syntax error before: ?\n

iex(tmate@erl_node_name)3> % Mix.Task.rerun("ecto.migrate", ["-r", Tmate.Repo, "--migrations-path", "./lib/tmate-0.1.1/priv/repo/migrations"])
...(tmate@erl_node_name)3> 16:04:00.001 [info] Pruning dead sessions older than 1 week
16:04:00.001 [info] Checking for disconnected sessions
16:04:00.005 [error] Task #PID<0.2290.0> started from #PID<0.2288.0> terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "sessions" does not exist

    query: DELETE FROM "sessions" AS s0 WHERE (s0."disconnected_at" < $1::timestamp + ($2::numeric * interval '1 week')) RETURNING s0."id"
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:177: Ecto.Repo.Queryable.execute/4
    (tmate) lib/tmate/session_cleaner.ex:19: Tmate.SessionCleaner.prune_sessions/1
    (quantum) lib/quantum/executor.ex:141: anonymous fn/3 in Quantum.Executor.run/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<7.12665260/0 in Quantum.Executor.run/4>
    Args: []
16:04:00.006 [error] Task #PID<0.2291.0> started from #PID<0.2289.0> terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "sessions" does not exist

    query: SELECT s0."id", s0."generation", s0."ws_url_fmt" FROM "sessions" AS s0 WHERE (s0."disconnected_at" IS NULL)
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:177: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (tmate) lib/tmate/session_cleaner.ex:32: Tmate.SessionCleaner.check_for_disconnected_sessions/1
    (quantum) lib/quantum/executor.ex:141: anonymous fn/3 in Quantum.Executor.run/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
Function: #Function<7.12665260/0 in Quantum.Executor.run/4>
    Args: []
16:05:00.002 [info] Checking for disconnected sessions
16:05:00.002 [info] Pruning dead sessions older than 1 week
16:05:00.005 [error] Task #PID<0.2295.0> started from #PID<0.2293.0> terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "sessions" does not exist

    query: DELETE FROM "sessions" AS s0 WHERE (s0."disconnected_at" < $1::timestamp + ($2::numeric * interval '1 week')) RETURNING s0."id"
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:177: Ecto.Repo.Queryable.execute/4
    (tmate) lib/tmate/session_cleaner.ex:19: Tmate.SessionCleaner.prune_sessions/1
    (quantum) lib/quantum/executor.ex:141: anonymous fn/3 in Quantum.Executor.run/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<7.12665260/0 in Quantum.Executor.run/4>
    Args: []
16:05:00.008 [error] Task #PID<0.2294.0> started from #PID<0.2292.0> terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "sessions" does not exist

    query: SELECT s0."id", s0."generation", s0."ws_url_fmt" FROM "sessions" AS s0 WHERE (s0."disconnected_at" IS NULL)
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:177: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (tmate) lib/tmate/session_cleaner.ex:32: Tmate.SessionCleaner.check_for_disconnected_sessions/1
    (quantum) lib/quantum/executor.ex:141: anonymous fn/3 in Quantum.Executor.run/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
Function: #Function<7.12665260/0 in Quantum.Executor.run/4>
    Args: []


^C[root@support tmate]# ^C
[root@support tmate]#
[root@support tmate]#
[root@support tmate]# docker-compose up -d
tmate_postgres_1 is up-to-date
Creating tmate_websocket_1 ... done
Creating tmate_ssh_1       ... done
Creating tmate_master_1    ... done
[root@support tmate]# docker-compose logs -f
Attaching to tmate_master_1, tmate_ssh_1, tmate_websocket_1, tmate_postgres_1
ssh_1        | Loading key /keys/ssh_host_rsa_key
ssh_1        | Loading key /keys/ssh_host_ed25519_key
ssh_1        | Accepting connections on :22
ssh_1        | fatal: Cannot connect to websocket server at websocket:4002
ssh_1        | fatal: Cannot connect to websocket server at websocket:4002
postgres_1   | The files belonging to this database system will be owned by user "postgres".
postgres_1   | This user must also own the server process.
postgres_1   |
postgres_1   | The database cluster will be initialized with locale "en_US.utf8".
postgres_1   | The default database encoding has accordingly been set to "UTF8".
postgres_1   | The default text search configuration will be set to "english".
postgres_1   |
postgres_1   | Data page checksums are disabled.
postgres_1   |
postgres_1   | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1   | creating subdirectories ... ok
postgres_1   | selecting default max_connections ... 100
postgres_1   | selecting default shared_buffers ... 128MB
postgres_1   | selecting default timezone ... Etc/UTC
postgres_1   | selecting dynamic shared memory implementation ... posix
postgres_1   | creating configuration files ... ok
postgres_1   | running bootstrap script ... ok
postgres_1   | performing post-bootstrap initialization ... ok
postgres_1   | syncing data to disk ... ok
postgres_1   |
postgres_1   | Success. You can now start the database server using:
postgres_1   |
postgres_1   |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1   |
postgres_1   |
postgres_1   | WARNING: enabling "trust" authentication for local connections
postgres_1   | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1   | --auth-local and --auth-host, the next time you run initdb.
postgres_1   | waiting for server to start....2020-08-14 16:03:10.190 UTC [45] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1   | 2020-08-14 16:03:10.208 UTC [46] LOG:  database system was shut down at 2020-08-14 16:03:10 UTC
postgres_1   | 2020-08-14 16:03:10.212 UTC [45] LOG:  database system is ready to accept connections
postgres_1   |  done
postgres_1   | server started
postgres_1   | CREATE DATABASE
postgres_1   |
postgres_1   |
postgres_1   | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1   |
postgres_1   | 2020-08-14 16:03:10.615 UTC [45] LOG:  received fast shutdown request
postgres_1   | waiting for server to shut down....2020-08-14 16:03:10.616 UTC [45] LOG:  aborting any active transactions
postgres_1   | 2020-08-14 16:03:10.619 UTC [45] LOG:  worker process: logical replication launcher (PID 52) exited with exit code 1
postgres_1   | 2020-08-14 16:03:10.619 UTC [47] LOG:  shutting down
postgres_1   | 2020-08-14 16:03:10.628 UTC [45] LOG:  database system is shut down
postgres_1   |  done
postgres_1   | server stopped
postgres_1   |
postgres_1   | PostgreSQL init process complete; ready for start up.
postgres_1   |
postgres_1   | 2020-08-14 16:03:10.731 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1   | 2020-08-14 16:03:10.731 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1   | 2020-08-14 16:03:10.733 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1   | 2020-08-14 16:03:10.748 UTC [63] LOG:  database system was shut down at 2020-08-14 16:03:10 UTC
postgres_1   | 2020-08-14 16:03:10.752 UTC [1] LOG:  database system is ready to accept connections
postgres_1   | 2020-08-14 16:04:00.002 UTC [79] ERROR:  relation "sessions" does not exist at character 55
postgres_1   | 2020-08-14 16:04:00.002 UTC [79] STATEMENT:  SELECT s0."id", s0."generation", s0."ws_url_fmt" FROM "sessions" AS s0 WHERE (s0."disconnected_at" IS NULL)
postgres_1   | 2020-08-14 16:04:00.003 UTC [84] ERROR:  relation "sessions" does not exist at character 13
postgres_1   | 2020-08-14 16:04:00.003 UTC [84] STATEMENT:  DELETE FROM "sessions" AS s0 WHERE (s0."disconnected_at" < $1::timestamp + ($2::numeric * interval '1 week')) RETURNING s0."id"
postgres_1   | 2020-08-14 16:05:00.003 UTC [75] ERROR:  relation "sessions" does not exist at character 13
postgres_1   | 2020-08-14 16:05:00.003 UTC [75] STATEMENT:  DELETE FROM "sessions" AS s0 WHERE (s0."disconnected_at" < $1::timestamp + ($2::numeric * interval '1 week')) RETURNING s0."id"
postgres_1   | 2020-08-14 16:05:00.003 UTC [76] ERROR:  relation "sessions" does not exist at character 55
postgres_1   | 2020-08-14 16:05:00.003 UTC [76] STATEMENT:  SELECT s0."id", s0."generation", s0."ws_url_fmt" FROM "sessions" AS s0 WHERE (s0."disconnected_at" IS NULL)
postgres_1   | 2020-08-14 16:06:00.003 UTC [78] ERROR:  relation "sessions" does not exist at character 55
postgres_1   | 2020-08-14 16:06:00.003 UTC [78] STATEMENT:  SELECT s0."id", s0."generation", s0."ws_url_fmt" FROM "sessions" AS s0 WHERE (s0."disconnected_at" IS NULL)
postgres_1   | 2020-08-14 16:06:00.004 UTC [81] ERROR:  relation "sessions" does not exist at character 13
postgres_1   | 2020-08-14 16:06:00.004 UTC [81] STATEMENT:  DELETE FROM "sessions" AS s0 WHERE (s0."disconnected_at" < $1::timestamp + ($2::numeric * interval '1 week')) RETURNING s0."id"
ssh_1        | fatal: Cannot connect to websocket server at websocket:4002
websocket_1  | [info] Starting websocket server
master_1     | 16:06:53.438 [info] [swarm on tmate@erl_node_name] [tracker:init] started
master_1     | 16:06:53.491 [info] Running TmateWeb.Endpoint with cowboy 2.7.0 at 0.0.0.0:4000 (http)
master_1     | 16:06:53.505 [info] Access TmateWeb.Endpoint at http://tmate.miner.farm:4000
ssh_1        | [zpHz...] Spawning daemon ip=100.14.72.228
ssh_1        | [zpHz...] tmate version=2.4.0, protocol=6
ssh_1        | [zpHz...] sysname=Linux machine=x86_64 release=5.0.0-31-generic version=#33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 nodename=pimp3
websocket_1  | token=[fm48...] id=ac4229be-de45-11ea-b26e-0242ac190003 [info] Session reconnected (count=1)
ssh_1        | [zpHz...] fatal: Connection to websocket server closed
websocket_1  | token=[fm48...] id=ac4229be-de45-11ea-b26e-0242ac190003 [error] GenServer #PID<0.1325.0> terminating
websocket_1  | ** (MatchError) no match of right hand side value: {:error, :enoent}
websocket_1  |     (tmate) lib/tmate/session.ex:183: Tmate.Session.rename_tmux_sockets!/4
websocket_1  |     (tmate) lib/tmate/session.ex:311: Tmate.Session.finalize_session_init/1
websocket_1  |     (tmate) lib/tmate/session.ex:131: Tmate.Session.handle_call/3
websocket_1  |     (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
websocket_1  |     (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
websocket_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
websocket_1  | Last message (from #PID<0.1324.0>): {:notify_daemon_msg, [1, '\t']}
websocket_1  | State: %{clients: %{}, current_layout: [], daemon: {Tmate.DaemonTcp, {#PID<0.1324.0>, #Port<0.10>, :ranch_tcp}}, daemon_protocol_version: 6, foreground: false, init_state: %{client_version: "2.4.0", ip_address: "100.14.72.228", named_session: %{api_key: nil, ro: nil, rw: nil}, reconnection_data: [2, "ac4229be-de45-11ea-b26e-0242ac190003", "fm483QZjhhwBu3yaHswRxKpRJ", "ro-6kvgtVscBcptf2MkuAcfCUdUL", "erl_node_name", 2], ssh_cmd_fmt: "ssh %s@tmate.miner.farm", stoken: "zpHzSX5dEJzhkHVuyDEmM5h3G", stoken_ro: "ro-pSfgd5asAB76tea5jLhukaVzF", uname: %{machine: "x86_64", nodename: "pimp3", release: "5.0.0-31-generic", sysname: "Linux", version: "#33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019"}, user_webhook_opts: [url: nil, userdata: ""]}, initialized: false, pending_ws_subs: [], registry: {Tmate.SessionRegistry, Tmate.SessionRegistry}, ssh_only: false, webhook_pids: [], webhooks: [{Tmate.Webhook, [url: "http://master:4000/internal_api/webhook", userdata: "internal_api_auth_token"]}], ws_subs: []}
websocket_1  | Client #PID<0.1324.0> is alive
websocket_1  |
websocket_1  |     (stdlib) gen.erl:167: :gen.do_call/4
websocket_1  |     (elixir) lib/gen_server.ex:1006: GenServer.call/3
websocket_1  |     (tmate) lib/tmate/daemon_tcp.ex:41: Tmate.DaemonTcp.receive_data/2
websocket_1  |     (tmate) lib/tmate/daemon_tcp.ex:25: Tmate.DaemonTcp.handle_info/2
websocket_1  |     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
websocket_1  |     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
websocket_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
websocket_1  | [error] Ranch listener :daemon_tcp had connection process started with Tmate.DaemonTcp:start_link/4 at #PID<0.1324.0> exit with reason: {{:badmatch, {:error, :enoent}}, [{Tmate.Session, :rename_tmux_sockets!, 4, [file: 'lib/tmate/session.ex', line: 183]}, {Tmate.Session, :finalize_session_init, 1, [file: 'lib/tmate/session.ex', line: 311]}, {Tmate.Session, :handle_call, 3, [file: 'lib/tmate/session.ex', line: 131]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
websocket_1  |
ssh_1        | [EXfu...] Spawning daemon ip=100.14.72.228
ssh_1        | [EXfu...] tmate version=2.4.0, protocol=6
ssh_1        | [EXfu...] sysname=Linux machine=x86_64 release=5.0.0-31-generic version=#33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 nodename=pimp3
ssh_1        | [EXfu...] fatal: Connection to websocket server closed
websocket_1  | token=[fm48...] id=ac4229be-de45-11ea-b26e-0242ac190003 [info] Session reconnected (count=1)
websocket_1  | token=[fm48...] id=ac4229be-de45-11ea-b26e-0242ac190003 [error] GenServer #PID<0.1327.0> terminating
websocket_1  | ** (MatchError) no match of right hand side value: {:error, :enoent}
websocket_1  |     (tmate) lib/tmate/session.ex:183: Tmate.Session.rename_tmux_sockets!/4
websocket_1  |     (tmate) lib/tmate/session.ex:311: Tmate.Session.finalize_session_init/1
websocket_1  |     (tmate) lib/tmate/session.ex:131: Tmate.Session.handle_call/3
websocket_1  |     (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
websocket_1  |     (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
websocket_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
websocket_1  | Last message (from #PID<0.1326.0>): {:notify_daemon_msg, [1, '\t']}
websocket_1  | State: %{clients: %{}, current_layout: [], daemon: {Tmate.DaemonTcp, {#PID<0.1326.0>, #Port<0.11>, :ranch_tcp}}, daemon_protocol_version: 6, foreground: false, init_state: %{client_version: "2.4.0", ip_address: "100.14.72.228", named_session: %{api_key: nil, ro: nil, rw: nil}, reconnection_data: [2, "ac4229be-de45-11ea-b26e-0242ac190003", "fm483QZjhhwBu3yaHswRxKpRJ", "ro-6kvgtVscBcptf2MkuAcfCUdUL", "erl_node_name", 2], ssh_cmd_fmt: "ssh %s@tmate.miner.farm", stoken: "EXfuTjqFYNFkvtXFhv6xDqsAw", stoken_ro: "ro-YSH6h8SJKwknRWXUJpcGra4fK", uname: %{machine: "x86_64", nodename: "pimp3", release: "5.0.0-31-generic", sysname: "Linux", version: "#33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019"}, user_webhook_opts: [url: nil, userdata: ""]}, initialized: false, pending_ws_subs: [], registry: {Tmate.SessionRegistry, Tmate.SessionRegistry}, ssh_only: false, webhook_pids: [], webhooks: [{Tmate.Webhook, [url: "http://master:4000/internal_api/webhook", userdata: "internal_api_auth_token"]}], ws_subs: []}
websocket_1  | Client #PID<0.1326.0> is alive
websocket_1  |
websocket_1  |     (stdlib) gen.erl:167: :gen.do_call/4
websocket_1  |     (elixir) lib/gen_server.ex:1006: GenServer.call/3
websocket_1  |     (tmate) lib/tmate/daemon_tcp.ex:41: Tmate.DaemonTcp.receive_data/2
websocket_1  |     (tmate) lib/tmate/daemon_tcp.ex:25: Tmate.DaemonTcp.handle_info/2
websocket_1  |     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
websocket_1  |     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
websocket_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
websocket_1  | [error] Ranch listener :daemon_tcp had connection process started with Tmate.DaemonTcp:start_link/4 at #PID<0.1326.0> exit with reason: {{:badmatch, {:error, :enoent}}, [{Tmate.Session, :rename_tmux_sockets!, 4, [file: 'lib/tmate/session.ex', line: 183]}, {Tmate.Session, :finalize_session_init, 1, [file: 'lib/tmate/session.ex', line: 311]}, {Tmate.Session, :handle_call, 3, [file: 'lib/tmate/session.ex', line: 131]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
websocket_1  |
master_1     | 16:06:58.438 [info] [swarm on tmate@erl_node_name] [tracker:cluster_wait] joining cluster..
master_1     | 16:06:58.438 [info] [swarm on tmate@erl_node_name] [tracker:cluster_wait] no connected nodes, proceeding without sync



```

**Comment by arjo-xfa** [comment]
Hi,

I have the same problem. Do you find any solution ?

Regards

**Comment by melt7777** [comment]
> Hi,
> 
> I have the same problem. Do you find any solution ?
> 
> Regards

Hi Arjo, 
Author must have abandoned us. I have not found solution on my own yet. But I will post it here if I do.

Thanks
~ melt

**Comment by kkoralsky** [comment]
@melt7777 @arjo-xfa sorry for inclarity  `%` is not meant to be treated as part of a command but just a command promptd

**Comment by melt7777** [comment]
Great - Thank you so much for your answer! Can you help us fix that bug in your scripts and get these pods up and running? Or update the instructions?  I'm not sure how to proceed based on your reply. Much appreciated. as always!

Thanks,
~ melt

**Comment by kkoralsky** [comment]
Ive already removed `%` to avoid confusion in readme this should be enough. The error you get inside the erlang console is probably due to the fact that some components of the service are already started in background and they complain that database is empty at the moment (w/o migrations yet).

**Comment by melt7777** [comment]
Thanks so much! This has resolved my issue.
